server:
  port: 8088


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/admin4j?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000ms

    lettuce:
      pool:
        max-wait: 10000ms
        max-active: 8
        max-idle: 8
        min-idle: 0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


admin4j:
  api:
    sign:
      enable:
        false
#  cache:
#    local:
#      enable:
#        true
#    distributed:
#      enable:
#        true

secure:
  ignored:
    urls: #安全路径白名单
      - /doc.html
      - /api-docs-ext
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /druid/**
      - /actuator/**
      - /sso/**
      - /v2/api-docs-ext

mybatis-plus:
  typeEnumsPackage: andanyoung.admin4j.enums
  global-config:
    db-config:
      id-type: auto
    banner: false
  mapper-locations: classpath:mappers:mapper/*.xml
