server:
  port: 8088


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/admin4j?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  profiles:
    active: dev

admin:
  api:
    sign:
      enable:
        false




