server:
  port: 8088


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/admin4j?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

admin:
  api:
    sign:
      enable:
        false

secure:
  ignored:
    urls: #安全路径白名单
      - /doc.html
      - /api-docs-ext
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /druid/**
      - /actuator/**
      - /sso/**
      - /v2/api-docs-ext


